name: client
description: "Real-Time Audio Platform PoC Flutter Client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  web_socket_channel: any
  provider: any
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  dart_webrtc: ^1.8.1
